{% set name = "fortranformat" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8c41ab39bb40444e6ca17f38755d64df51799b064206833c137a28bbdca1b2b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - fortranformat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brendanarnold/py-fortranformat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mimics Fortran textual IO in Python
  description: "FORTRAN format interpreter for Python.\nGenerates text from a Python list of variables or will read a line of text into Python variables according to the FORTRAN format statement passed."
  doc_url: https://github.com/brendanarnold/py-fortranformat/blob/master/docs/wiki/guide.md
  dev_url: https://github.com/brendanarnold/py-fortranformat

extra:
  recipe-maintainers:
    - smithsp
    - alexmalins
