travis:
  secure:
    BINSTAR_TOKEN: mURUTbpKqP7EMBe/DyT2/mEFBpID4QLgR5MIMBiUp2h/qq00j5izw/Em1nA/RS/DWRBJt/QBhrsDzhnim2JmbBOV9PgdSQwO3vwSNkAn9aebu3wqK8jKZ4FCgWh0TC8VS6jjCbhpud/TDQ8MZFXv7tnCa2DcqXywxxx3jsNAHJ/ypGq7QjF9Yye0VPxf+A4OAi0mssk4LL/FHDcUqHQfTjNlLtdhSWGgCfayogDqdbmY1lTwLkGcLpN0//pqwPPWit/1JoBA/JiIO8vonT7TnnpHNwgPX7QYE13H3vsZLzuKK3T1vyJWBtqwXhGscNDWGgZfLx00Q+FSP6cxyxlOP0X7i6bcXAYaXD86oEjwFO0wcCBKYRsDjFq5cdZxyQcRx2rjgV7E1RL6fjrMbHowj4QRntbbqkbI1z/X3Reho28tNtNL6lQoQjdJzbca4QNopTj4pwm10ejfw6DLdRMChyWi4TpK51GcKXHWQSLntAecpKTcokvvytojQiXQyX8EYdPMDWT2ru6qiW42kv2oeq+/M4c7IwBElCSlBmQ/UQVa/9+ToNk+IjcyZ3sJj55y4I5pbBfKMmM/oIIfkb/E4oDygQ57qRXVJJNPFl3hsLMXx4mPuN789FooDGyLduQxAHQTYWsGSB/7HJWDCbbGGjbxaORq61Oj2qjSJRioEwU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
