travis:
  secure:
    BINSTAR_TOKEN: JzQAMzYA5t/P9pUXhU5rTYW5G05xb2BFWOEbTZ/pS/KXWTq1SYll2K4BOXJYI35AZlvmwUP9JLu8H3CDDGvb9ANTKlzxlsCrIoyL9qf7K8C2TzjB8Rd8Vii8DKFv9So533cmPSDU8pvO2PQcwVSIYbsW/fFCbzsdphQ7Ktey0B0hKXLcJaZzFs+c/PGqjsR6wnUpcoyRc+ArObF3xM3SjkRPkD/5rD26xr+aUEElFkNTbXGlgxDBZi0ijdPsvPCOqzpO+l9pvi7t6/xpAAT+mOmgxO7cPy7F1tNcs/10ZsB4mvmsb0KBtf/wmHXTmEBYQZb+jGfD9+If3FYW5y9HYAbZZjStzsMWzXpowWK916GKKvitQZUG6LRtxfxAs7qPOrYLgc6NQ3ej5SdT4mj5OQMLz82sFg/OxFai1YxlNLNCsOLk+NZnOY54a0nm+HVAcc+XvAAZyoIzpdHO8dpcrDO2f2wr9Fz/7s0NcbXBKETB1KuylxU3JZVwUEn27kRVerO6i4igclm7MLvm0d+GQO7+UW5EOe8+TpFuubT/Ikq3jiZKQqHlah+/9MD7DWl2OYlH1nTSFgseKkPpwJxNHIaliNV8lVxxklxGWHEVOFa1xEUKe08TLOAegbCVpZ4qpGJCHDyz6499t8icGJObRdJna//v67KitjeB5CMfaQo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
